config/routes.rb
Rails.application.routes.draw do
  get 'users/show'

  get 'tp_en/:tokipona_phrase_id/(:practical_role)' => 'english_phrases#from_tokipona', as: :tp_en, defaults: { format: 'json'}

  resources :documents do
    resources :translations, shallow: true
  end

  resources :translations, only: [ :index ]

  devise_for :users, path_names: {
    sign_in: 'login',
    sign_out: 'logout'
  }

  resources :users, only: [ :show ]
  

  root 'documents#index'

end

app/models/translation.rb
class Translation < ActiveRecord::Base
  require 'json'
  include GrammarHelper
  include EachHead

  belongs_to :user
  belongs_to :document
  has_many :segments, class_name: 'TranslationSegment', dependent: :destroy

  after_initialize :prepare_analysis
  after_save :create_translation_segments

  validate :analysis_must_be_in_proper_format

  private

  def words_array
    document.words.split ','
  end

  def prepare_analysis
    # self.analysis = scaffold_translations(document.parsed_tree).to_json
    self.analysis = document.parsed_tree.map { |sentence|
      scaffold_translations(sentence)
    }.to_json
  end

  def get_role(head_parent)
    return 't' if head_parent.keys.include?('direct_objects')
    return 'prep' if head_parent.keys.include?('prepositional_object')
    return 'i'
  end

  # check for erroneously capitalize tp words eventually.
  def scaffold_translations(the_tree)
    translations = []
    each_head(the_tree) do |tp_word, parent|
      if native_tokipona?(tp_word)
        role = get_role(parent)
        # tp = TokiponaPhrase.find_by(words: principal_tokipona_form(tp_word), role: role) # ACCOUNT FOR ROLE
        tp = TokiponaPhrase.where('words = ?', principal_tokipona_form(tp_word)).find_in_role(role).first
      else
        # make or find proper noun
        tp = TokiponaPhrase.find_or_create_by(words: tp_word.capitalize, role: 'i')
      end
      byebug if tp.nil?
      english_phrase = EnglishPhrase.find_by(tokipona_phrase_id: tp.id)

      translations.push(
        tp: tp.words,
        tp_role: tp.role,
        tp_id: tp.id,
        en: english_phrase.nil? ? nil : english_phrase.base_form,
        en_id: english_phrase.nil? ? nil : english_phrase.id
        )
    end
    translations
  end

  def create_translation_segments
    # safe_segments.each do |segment|
    #   segments.create(place: segment[0], english_phrase_id: segment[1], english_form: segment[2])
    # end
  end

  def analysis_array
    if translation_segments.is_a? Array
      translation_segments
    else
      JSON.parse translation_segments
    end
  end

  def analysis_must_be_in_proper_format
  end

end

app/controllers/translations_controller.rb
class TranslationsController < ApplicationController
  before_action :set_translation, only: [:show, :edit, :update, :destroy]
  before_action :set_document
  before_action :authenticate_user!, except: [:index, :show, :new]
  before_action :own_translation, only: [:edit, :update, :destroy]


  # GET /translations
  # GET /translations.json
  def index
    @translations = @document ? @document.translations : Translation.all
  end

  # GET /translations/1
  # GET /translations/1.json
  def show
  end

  # GET /translations/new
  def new
    @translation = @document.translations.build
  end

  # GET /translations/1/edit
  def edit
  end

  # POST /translations
  # POST /translations.json
  def create
    @translation = @document.translations.new(translation_params)
    @translation.user_id = current_user.id

    respond_to do |format|
      if @translation.save
        format.html { redirect_to @translation, notice: 'Translation was successfully created.' }
        format.json { render :show, status: :created, location: @translation }
      else
        format.html { render :new }
        format.json { render json: @translation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /translations/1
  # PATCH/PUT /translations/1.json
  def update
    respond_to do |format|
      if @translation.update(translation_params)
        format.html { redirect_to @translation, notice: 'Translation was successfully updated.' }
        format.json { render :show, status: :ok, location: @translation }
      else
        format.html { render :edit }
        format.json { render json: @translation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /translations/1
  # DELETE /translations/1.json
  def destroy
    @translation.destroy
    respond_to do |format|
      format.html { redirect_to translations_url, notice: 'Translation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_translation
      @translation = Translation.find(params[:id])
    end

    def set_document
      @document = params[:document_id] ? Document.find(params[:document_id]) : nil
    end

    def own_translation
      unless current_user == @translation.user
        redirect_to @translation
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def translation_params
      params.require(:translation).permit(:user_id, :document_id, :translation_segments)
    end
end

app/helpers/translations_helper.rb
module TranslationsHelper
end

app/views/translations/_form.html.erb
<% content_for(:ng_controller, 'translationController as translation') %>
<% content_for(:body_class, 'global-events') %>

<script>
  app.value('analysis', <%= raw @translation.analysis %>);
  app.value('documentAnalysis', <%= raw @translation.document.tree %>)
</script>

<%= form_for [@document, @translation] do |f| %>
  <% if @translation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@translation.errors.count, "error") %> prohibited this translation from being saved:</h2>

      <ul>
      <% @translation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <translation></translation>

  <div class="field">
    <%= f.label :analysis %><br>
    <%= f.text_area :analysis %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/translations/edit.html.erb
<h1>Editing Translation</h1>

<%= render 'form' %>

<%= link_to 'Show', @translation %> |
<%= link_to 'Back', translations_path %>

app/views/translations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Translations</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Document</th>
      <th>Analysis</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @translations.each do |translation| %>
      <tr>
        <td><%= translation.user %></td>
        <td><%= translation.document %></td>
        <td><%= translation.analysis %></td>
        <td><%= link_to 'Show', translation %></td>
        <td><%= link_to 'Edit', edit_translation_path(translation) %></td>
        <td><%= link_to 'Destroy', translation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/translations/new.html.erb
<h1><%= @translation.document.title %></h1>

<%= render 'form' %>

<%= link_to 'Back', translations_path %>

app/views/translations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @translation.user %>
</p>

<p>
  <strong>Document:</strong>
  <%= @translation.document %>
</p>

<p>
  <strong>Translation segments:</strong>
  <%= @translation.analysis %>
</p>

<%= link_to 'Edit', edit_translation_path(@translation) %> |
<%= link_to 'Back', translations_path %>