config/routes.rb
Rails.application.routes.draw do
  get 'users/show'

  get 'tp_en/:tokipona_phrase_id/(:practical_role)' => 'english_phrases#from_tokipona', as: :tp_en, defaults: { format: 'json'}

  resources :documents do
    resources :translations, shallow: true
  end

  resources :translations, only: [ :index ]

  devise_for :users, path_names: {
    sign_in: 'login',
    sign_out: 'logout'
  }

  resources :users, only: [ :show ]
  

  root 'documents#index'

end

app/models/document.rb
class Document < ActiveRecord::Base
	require 'json'
	include EachHead

  belongs_to :user
  has_many :translations, dependent: :destroy

  validates :title, presence: true
  validates :original_text, presence: true

  before_save :set_tree, :prepare_words, :index_heads

  def set_tree
  	require 'tokipona'
  	self.tree = Parsing.new(original_text).json
  end

  # private

  def index_heads
  end

	def prepare_words
		extraction = []
		JSON.parse(tree).each do |sentence|
			extraction += extract_words(sentence)
		end
		self.words = extraction.join ','
	end

	def parsed_tree
		@parsed_tree ||= JSON.parse(tree)
	end

	def extract_words(collection)
		heads = []
		each_head(collection) do |e|
			heads += extract_words(e)
		end
		heads
	end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show, :new]
  before_action :own_document, only: [:edit, :update, :destroy]

  # GET /documents
  # GET /documents.json
  def index
    @documents = Document.page(params[:page]).per 10
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
  end

  # GET /documents/new
  def new
    @document = current_user.documents.build
  end

  # GET /documents/1/edit
  def edit
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = current_user.documents.build(document_params)

    respond_to do |format|
      if @document.save
        format.html { redirect_to @document, notice: 'Document was successfully created.' }
        format.json { render :show, status: :created, location: @document }
      else
        format.html { render :new }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1
  # PATCH/PUT /documents/1.json
  def update
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to @document, notice: 'Document was successfully updated.' }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document.destroy
    respond_to do |format|
      format.html { redirect_to documents_url, notice: 'Document was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def document_params
      params.require(:document).permit(:user_id, :title, :original_text)
    end

    def own_document
      unless current_user == @document.user
        redirect_to @document
      end
    end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_form.html.erb
<%= form_for(@document) do |f| %>
  <% if @document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
      <% @document.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :original_text %><br>
    <%= f.text_area :original_text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/documents/edit.html.erb
<h1>Editing Document</h1>

<%= render 'form' %>

<% if @document.user == current_user %>
<%= link_to 'Delete', document_path(@document), method: 'delete' %> | 
<% end %>
<%= link_to 'Show', @document %> |
<%= link_to 'Back', documents_path %>

app/views/documents/index.html.erb
<% content_for :body_class, 'documents index' %>

<h1>lipu pi toki pona <small>Toki Pona texts</small></h1>

<%= paginate @documents %>

<ul id="documents-list">
  
  <% @documents.each do |document| %>

  <li>
    <h2><%= link_to document.title, document %></h2>
    <p>by <%= link_to document.user.username, "#" %></p>
    <p><%= truncate(document.original_text, length: 140, omission: '...', separator: ' ') %>
    	<%= link_to('awen', document) %></p>
  </li>

  <% end %>

</ul>


<%= link_to 'New Document', new_document_path %>

app/views/documents/new.html.erb
<h1>New Document</h1>

<%= render 'form' %>

<%= link_to 'Back', documents_path %>

app/views/documents/show.html.erb
<% content_for :ng_controller, "showDocumentController" %>

<h1><%= @document.title %></h1>

<p>
  jan <%= @document.user.username %> li pali e ni.
  <br>
  <small>by <%= @document.user.username %></small>
</p

<p>
  <div id="text" class="syntax-highlight"><tp-sentence ng-repeat="sen in documentAnalysis" sen="sen"><%= @document.original_text %></tp-sentence></div>
</p>


<%= link_to 'Translate', new_document_translation_path(@document) %> |
<% if @document.user == current_user %>
<%= link_to 'Edit', edit_document_path(@document) %> | 
<% end %>
<%= link_to 'Back', documents_path %>

<script>
app.value('documentAnalysis', <%= raw(@document.tree) %>);

window.jsonObj = <%= raw(@document.tree) %>;
window.orig = '<%= j(@document.original_text) %>';
console.log(window.orig)
</script>